title: "Deploy a containerized Theia instance on OCI"
description: "Deploy containerized Theia & MySQL on OCI using a single compute instance. "
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region

- title: Theia Configuration
  visible: true  
  variables:
    - show_advanced

- title: MySQL Configuration
  visible: 
      and:
        - show_advanced  
  variables:
    - mysql_root_password
    - nc_db_user
    - nc_db_password
    - nc_schema



- title: Instance Configuration
  visible: 
      and:
        - show_advanced
  variables:
    - compartment_id
    - availability_domain_name 
    - node_shape
    - instance_os
    - linux_os_version
    - generate_public_ssh_key
    - public_ssh_key


- title: Network Configuration
  visible: 
      and:
        - show_advanced
  variables:
     - vcn
     - vcn_cidr

outputGroups:
- title: Service Endpoints
  outputs:
    - theia_public_ip
- title: Generated Passwords
  outputs:
    - generated_ssh_private_key

outputs:
  theia_public_ip:
    type: link
    title: Your Theia website
    description: Open Theia website
  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    description: "Generated SSH Private Key"
    type: copyableString
    visible: true

primaryOutputButton: theia_public_ip

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

# MySQL
  mysql_root_password:
    type: password
    required: false
    visible: 
      and:
        - show_advanced
    title: "MySQL admin password"
    description: "Choose the password that will be set for the MySQL root superuser account."
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  nc_db_user:
    type: string
    required: false
    title: "Theia database username"
    description: "The username that Theia uses to connect to the MySQL database."
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: 
      and:
        - show_advanced

  nc_db_password:
    type: password
    required: false
    title: "Theia database password"
    description: "Password for Theia to connect to the MySQL database."
    #pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"
    visible: 
      and:
        - show_advanced

  nc_schema:
    type: string
    required: false
    title: "MySQL schema to be used by Theia"
    description: "The MySQL Schema/Database for Theia."
    visible: 
      and:
        - show_advanced

# Network
  vcn:
    type: string
    visible: 
      and:
        - show_advanced
    required: true
    title: "VCN name"
    description: "Type VCN name where your Theia will be deployed."

  vcn_cidr:
    type: string
    visible: 
      and:
        - show_advanced
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN CIDR for your Theia deployment."

# Instance 
  compartment_id:
    type: oci:identity:compartment:id
    required: true
    visible: 
      and:
        - show_advanced
    title: "Compartment"
    description: "Compartment where your Theia will be deployed."

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visible: 
      and:
        - show_advanced
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your Theia will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_id}

  node_shape:
    type: oci:core:instanceshape:name
    required: false
    visible: 
      and:
        - show_advanced
    title: "Theia node shape"
    description: "Choose Instance Shape for Theia host."
    default: "VM.Standard2.1"
    dependsOn:
      compartmentId: ${compartment_id}

  instance_os:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: "Instance OS"
    description: "An Operating System that determines the operating system for Theia host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for Theia host."
    default: "7.8"
    enum:
      - "7.8"

  label_prefix:
    type: string
    required: false
    visible: false
    title: "Theia Hostname Prefix"
    description: "Type Theia Hostname Prefix."

  

  generate_public_ssh_key:
    type: boolean
    title: "Auto generate public ssh key?"
    required: true
    visible: #($show_advanced  == ""Yes"")
      and:
        - show_advanced 

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH public key"
    additionalProps:
      allowMultiple: true
    description: "In order to access your private nodes with a public SSH key you will need to set up a bastion host (a.k.a. jump box). If using public nodes, bastion is not needed. Left blank to not import keys."
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible: 
      and:
        - show_advanced
        - not:
          - generate_public_ssh_key

